todo = Todo(name='vika', description='woman', user_id='1')
todo.save()
todo = Todo(name='katya', description='woman', user_id='1')
todo.save()
todo = Todo(name='vlad', description='man', user_id='1')
todo.save()
todo = Todo(name='andrei', description='man', user_id='1')
todo.save()
Todo.objects.all()
Todo.objects.all().values('id', 'name')
Todo.objects.get(id=1)
Todo.objects.filter(name='andr').values('name')